name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-smoke-test-image:
    name: Build Docker Image and Smoke Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag name-picker
      - name: Run the app in the Docker image
        run: docker run --rm -d -p 3000:3000 --name test-run name-picker

      - name: Install dependencies
        working-directory: ./end2end
        run: npm ci
      - name: Install Playwright Browsers
        working-directory: ./end2end
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        working-directory: ./end2end
        run: npx playwright test --reporter=line --max-failures=1
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: end2end/playwright-report/
          retention-days: 30

  build-rust:
    name: Test Rust code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Check
        run: cargo check --verbose --all-targets --all-features
      - name: Run clippy checks
        run: cargo clippy -- -D warnings
      - name: Run fmt checks
        run: cargo fmt --check
      - name: Run unit tests
        run: cargo test --verbose --all-targets
